db : Adicionando um novo modelo para a BD
risk-place-angola/backend-risk-place pull request #18
Opened 2023-03-04 10:10 UTC by edgarsingui

hmm um modelo provisório para a bd

2023-03-04 10:59 UTC, Paulo-Lopes-Estevao reviewed
@edgarsingui por questão de segurança e privacidade dos dados decidimos ainda não lidar com o processo da conta do usuário.

2023-03-04 11:01 UTC, Paulo-Lopes-Estevao commented
> @edgarsingui por questão de segurança e privacidade dos dados decidimos ainda não lidar com o processo da conta do usuário.

Essa é uma questão que podemos levar ao forúm de discussão.

2023-03-04 11:22 UTC, Paulo-Lopes-Estevao commented
No momento evitamos o processo de preenchimento de informações.
O projeto é Open Source o objetivo é ser aberto e fácil para quem e qualquer pessoa usar.
Ao envolvermos questões de armazenamento de dados pessoais > abreriamos um outro assunto que é **Protecção de Dados Pessoais**.

2023-03-04 11:23 UTC, Paulo-Lopes-Estevao commented
> No momento evitamos o processo de preenchimento de informações. O projeto é Open Source o objetivo é ser aberto e fácil para quem e qualquer pessoa usar. Ao envolvermos questões de armazenamento de dados pessoais > abreriamos um outro assunto que é **Protecção de Dados Pessoais**.

Mesmo assim essa é uma questão que podemos levar ao forúm de discussão futuramente.

2023-03-04 11:32 UTC, Paulo-Lopes-Estevao requested changes
@edgarsingui  Poderia dar mais detalhes ao fluxo de **Notificações**, quanto a sua implementação.
É um fluxo importante faz parte dos nossos requisitos.

2023-03-04 11:39 UTC, edgarsingui commented
@Paulo-Lopes-Estevao  ainda estou trabalhando no seu fluxo, brevemente irei actualizar.

2023-03-04 11:44 UTC, edgarsingui commented
> @edgarsingui Poderia dar mais detalhes ao fluxo de **Notificações**, quanto a sua implementação. É um fluxo importante faz parte dos nossos requisitos.

blz, irei actualizar o modelo com base os seus comentários, quanto às notificações ainda irei trabalhar mais no seu modelo.

2023-03-04 12:14 UTC, Paulo-Lopes-Estevao commented
> > @edgarsingui Poderia dar mais detalhes ao fluxo de **Notificações**, quanto a sua implementação. É um fluxo importante faz parte dos nossos requisitos.
> 
> blz, irei actualizar o modelo com base os seus comentários, quanto às notificações ainda irei trabalhar mais no seu modelo.

Boa @edgarsingui, estava a analisar aqui se envolvermos as **notificações** nível da base de dados teremos um pouquinho de problemas.
Olha na questão notificarmos locais de risco quando estivermos proximo, é só uma analise ao invéis vermos ele como um evento.

E notificações passamos para configurar

- Quantos alerta quer receber.
- Notificação de novos locais de risco.
- Notificação de ocorrencia.

2023-03-20 22:45 UTC, edgarsingui commented
Sim @Paulo-Lopes-Estevao  🤔

2023-03-22 11:04 UTC, edgarsingui commented
boas, irei ver e desenhar esse fluxo nesse feriado!

2023-07-06 02:05 UTC, closed without merging