fix: :bug: Corrigir mensagem de erro de login que não é exibida quand…
risk-place-angola/backend-risk-place pull request #64
Opened 2023-04-06 12:41 UTC by manuelcunga

## Descrição da PR
Corrigir mensagem de erro de login que não é exibida quando um e-mail incorreto é inserido

## Informações
* (issue) #

#### Tipo da PR
- [x] BUGFIX - Correções de problemas ou melhorias.

### Código
- [x] Desacoplado e isolado.
- [x] Não inclui comentários redundantes Ex.: `# Precisei alterar isso por conta disso`.
- [x] Enviei a demonstração da implementação (caso necessário).
- [x] Link para documentação da implementação (caso necessário).
- [ ] Atualização do `Readme.md` (caso necessário).
- [x] Não contem código em *WIP*, caso seja para `origin/master`.
- [ ] Requer instalação/atualização de dependências.
- [x] Contém testes automatizados.

### Merge
- [x] Estou seguindo o processo de GitFlow.
- [x] Estou seguindo as práticas descritas nos [guias de contribuição](../CONTRIBUTING.md)

### Aprovadores
- [x]  CC: @gentildpinto 
- [x]  CC: @Paulo-Lopes-Estevao 

### Informações adicionais

*Essa PR busca corrigir um bug que impede que a mensagem de erro seja exibida quando um e-mail incorreto é inserido durante o login. Com a correção, o usuário receberá uma mensagem de erro informando que o e-mail ou senha estão incorretos, garantindo uma melhor experiência de usuário. Essa correção é importante para garantir a segurança e confiabilidade do sistema de autenticação.*

2023-04-06 12:48 UTC, gentildpinto commented
@manuelcunga algum teste falhou

2023-04-06 12:57 UTC, gentildpinto requested changes
@manuelcunga um teste falhou

E por outra, estou um pouco confuso.
O pr é descrito como uma correção de alguma falha no fluxo de login, mas alterações foram feitas nos métodos para atualizar usuário, encontrar usuário por email e também houve alterações nos arquivos de dependências (go.mod e go.sum)

2023-04-06 13:06 UTC, manuelcunga commented
> @manuelcunga um teste falhou
> 
> E por outra, estou um pouco confuso. O pr é descrito como uma correção de alguma falha no fluxo de login, mas alterações foram feitas nos métodos para atualizar usuário, encontrar usuário por email e também houve alterações nos arquivos de dependências (go.mod e go.sum)

2023-04-06 13:11 UTC, manuelcunga commented
> @manuelcunga um teste falhou
>  testandoo
> E por outra, estou um pouco confuso. O pr é descrito como uma correção de alguma falha no fluxo de login, mas alterações foram feitas nos métodos para atualizar usuário, encontrar usuário por email e também houve alterações nos arquivos de dependências (go.mod e go.sum)

2023-04-06 13:38 UTC, manuelcunga commented
> atualizar usuár

Sim o go mod, deve ter vido, quando dei o tidy.
vou mudar a mensagem de commit, porque o metodo de atualização tinha erro também.

2023-04-06 13:42 UTC, gentildpinto commented
> > atualizar usuár
> 
> Sim o go mod, deve ter vido, quando dei o tidy. vou mudar a mensagem de commit, porque o metodo de atualização tinha erro também.

mas porquê commitar essa alteração nessa branch que segundo a descrição deveria ser para corrigir um bug no login?

2023-04-07 11:41 UTC, manuelcunga commented
> > > atualizar usuár
> > 
> > 
> > Sim o go mod, deve ter vido, quando dei o tidy. vou mudar a mensagem de commit, porque o metodo de atualização tinha erro também.
> 
> mas porquê commitar essa alteração nessa branch que segundo a descrição deveria ser para corrigir um bug no login?

Quis mandar tudo de uma vez, vou refazer por branch

2023-04-08 19:16 UTC, gentildpinto commented
> Quis mandar tudo de uma vez, vou refazer por branch

Então podemos dizer que este check é mentira?

![Screenshot 2023-04-08 at 20-14-42 fix bug Corrigir mensagem de erro de login que não é exibida quand… by manuelcunga · Pull Request #64 · risk-place-angola_backend-risk-place](https://user-images.githubusercontent.com/45848094/230738950-7e8ad980-94be-4159-a3e9-246a49132429.png)

2023-04-08 19:29 UTC, gentildpinto commented on infra/repository/user_repository.go
> +		if errors.Is(err, gorm.ErrRecordNotFound) {
Eu acho essa verificação desnecessária o erro precisa ser retornado, não importa o tipo

2023-04-08 19:36 UTC, gentildpinto requested changes

2023-04-08 19:36 UTC, gentildpinto commented on usecase/user/user_usecase.go
> +	if user == nil {
Quando se usa o método ```First``` do gorm, ele retorna sempre um erro quando o user não for encontrado, se o user não for encontrado significa que o email ou senha estão incorretos ou o user não existe

Então acredito ser também desnecessário verificar se a variável ```user``` é ```nil```

2023-04-08 19:36 UTC, gentildpinto commented on infra/repository/user_repository.go
> +		if errors.Is(err, gorm.ErrRecordNotFound) {
Eu acho essa verificação desnecessária o erro precisa ser retornado, não importa o tipo

2023-04-08 22:21 UTC, manuelcunga commented on usecase/user/user_usecase.go
> +	if user == nil {
> Quando se usa o método `First` do gorm, ele retorna sempre um erro quando o user não for encontrado, se o user não for encontrado significa que o email ou senha estão incorretos ou o user não existe
> 
> Então acredito ser também desnecessário verificar se a variável `user` é `nil`

Certo tem razão!

2023-04-08 22:22 UTC, manuelcunga commented on infra/repository/user_repository.go
> +		if errors.Is(err, gorm.ErrRecordNotFound) {
> Eu acho essa verificação desnecessária o erro precisa ser retornado, não importa o tipo

Verdade

2023-04-08 23:26 UTC, Paulo-Lopes-Estevao approved these changes

2023-04-08 23:26 UTC, Paulo-Lopes-Estevao approved these changes

2023-04-09 12:15 UTC, gentildpinto approved these changes

2023-04-09 12:44 UTC, merged